Since Beta1.1 there is a severe Memory Leak Problem. System76 didn't adressed this Bug yet. It is unclear, in which version it get fixed.
If you encounter this Bug, you can easiely Rollback to alpha7. You only need to type this command:

		sudo xbps-install cosmic-desktop-alpha

This installs you the last stable version of cosmic-desktop, which is alpha7, it automatically removes the packages with the newest Version
