#!/bin/bash
case "$ACTION" in
post)
	if [ "$UPDATE" = "no" ]; then
		xdg-user-dirs-update
		layout=$(grep 'KEYMAP=' /etc/rc.conf | cut -d= -f2)
mkdir -p /usr/share/cosmic/com.system76.CosmicComp/v1/
touch /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config
cat >> /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config <<EOF
(
rules: "",
model: "",
layout: "us",
variant: "",
options: None,
repeat_delay: 600,
repeat_rate: 25,
)
EOF
		sed -i "s/us/$layout/" /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config
		if [ ! -h /usr/bin/firefox ]; then
			sed -i 's/firefox//' /usr/share/cosmic/com.system76.CosmicAppList/v1/favorites
		fi
		if [ ! -d /etc/xdg/autostart ]; then
			mkdir -p /etc/xdg/autostart
			ln -s /usr/share/applications/wireplumber.desktop /etc/xdg/autostart/
			ln -s /usr/share/applications/pipewire\-pulse.desktop /etc/xdg/autostart/
			ln -s /usr/share/applications/pipewire.desktop /etc/xdg/autostart/
		else
			if [ ! -h /etc/xdg/autostart/pipewire.desktop ]; then
				ln -s /usr/share/applications/pipewire.desktop /etc/xdg/autostart/
			fi
			if [ ! -h /etc/xdg/autostart/pipewire\-pulse.desktop ]; then
				ln -s /usr/share/applications/pipewire\-pulse.desktop /etc/xdg/autostart/
			fi
			if [ ! -h /etc/xdg/autostart/wireplumber.desktop ]; then
				ln -s /usr/share/applications/wireplumber.desktop /etc/xdg/autostart
			fi
		fi
		if [ ! -d /etc/xdg-desktop-portal ]; then
			mkdir /etc/xdg-desktop-portal
		fi
		echo "$XDG_CURRENT_DESKTOP" > /etc/xdg-desktop-portal/xdg-desktop-portal.conf
		echo "default=cosmic" >> /etc/xdg-desktop-portal/xdg-desktop-portal.conf
		if [ -h /etc/sv/sddm ]; then
			if grep -q "InputMethod" /etc/sddm.conf; then
				sed -i "s/us/$layout/" /etc/sddm.conf
			else
				echo "[General]" >> /etc/sddm.conf
				echo "InputMethod=$layout" >> /etc/sddm.conf
			fi
		fi
	fi
	;;
esac
