====================================================
⚠️ Info about Cosmic Desktop Beta 1.1

This version is known for memory leaks Problems.
If you encounter this Problem too, you see it, if the desktop environemnt crashes regularly.
Then you can rollback to the alpha version, which is more stable with this command:

    sudo xbps-install -S cosmic-desktop-alpha

This will replace all beta components and will install the alpha version.
On the next stable beta version, you get automatically upgraded back
====================================================
