#!/usr/bin/env python3
import os
import subprocess, sys
from pwd import getpwuid

environmentvarslist = []
def getEnvironment():
    enviromentvarsnames = ["PATH", "DISPLAY", "XDG_DATA_DIRS WAYLAND_DISPLAY", "XDG_SESSION_ID", "XDG_SESSION_TYPE", "XDG_SEAT", "XDG_CURRENT_DESKTOP"]
    for f in enviromentvarsnames:
        g = os.environ.get(f, "None")
        if g == "None":
            continue
        environmentvar = f"{f}=\"{g}\""
        environmentvarslist.append(environmentvar)
    vartmpfile = open("/tmp/user-environment-vars", "w+")
    vartmpfilecontent = []
    for v in environmentvarslist:
        vartmpfilecontent.append(v + "\n")
    vartmpfile.writelines(vartmpfilecontent)
    vartmpfile.close()

def setEnvironment(run=""):
    uid = str(os.getuid())
    home = os.environ.get("HOME")
    vartmpfile = open("/tmp/user-environment-vars", "r")
    vartmpfilecontent = vartmpfile.readlines()
    vartmpfile.close()
    if not os.path.isdir(f"/run/user/{uid}/userctl"):
        os.mkdir(f"/run/user/{uid}/userctl")
    userenvfile = open(f"/run/user/{uid}/userctl/env", "w")
    userenvfile.writelines(vartmpfilecontent)
    userenvfile.close()
    source = False
    bashprofile = open(f"{home}/.bash_profile", "r")
    bashprofilecontent = bashprofile.readlines()
    bashprofile.close()
    bashprofile = open(f"{home}/.bash_profile", "a")
    for s in bashprofilecontent:
        if s.startswith("[ -f /run/user/$UID/userctl/env ] && source /run/user/$UID/userctl/env"):
            source = True
            break
    if not source:
        bashprofile.write("\n[ -f /run/user/$UID/userctl/env ] && source /run/user/$UID/userctl/env")
    if run:
        subprocess.run(run, shell=True, executable="/bin/bash")

def run(run):
        subprocess.run(run, shell=True, executable="/bin/bash")

if __name__ == '__main__':
    if len(sys.argv) >= 2:
        if sys.argv[1] == "get-environment":
            getEnvironment()
        elif sys.argv[1] == "set-environment":
            if len(sys.argv) == 3:
                setEnvironment(sys.argv[2])
            else:
                setEnvironment()
        elif sys.argv[1] == "run":
            if len(sys.argv) == 2:
                sys.stderr.write("You need to clarify the command which should be run\nUsage: userctl run [command]")
                exit(1)
            run(sys.argv[2])
        else:
            sys.stderr.write("False Agrument\nUsage: userctl [argument] (command)\nCommands:\nget-environment  To save the important environment variables.\nset-environment (command)  Injects the saved environment variables to user. run is optional\nrun [command]  runs a command")
    else:
        sys.stderr.write("No Arguments giving.\nUsage: userctl [argument] (command)\nCommands:\nget-environment  To save the important environment variables.\nset-environment (command)  Injects the saved environment variables to user. run is optional\nrun [command]  runs a command")
        exit(1)


